---
- name: This sets up an httpd webserver
  hosts: 192.168.50.11
  tasks:
  - name: install the latest version of Apache
    dnf:
      name: httpd
      state: latest
    become: yes
  - name: ensure httpd is running
    service:
      name: httpd 
      state: started
      enabled: yes
  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
